env = Environment(
    CXXFLAGS = "-g -Wall -O2 -std=c++1y -DUSE_PLUSTACHE",
    CPPPATH = ['/usr/include/eigen3'],
    LIBPATH = ['/usr/lib/OpenMesh'],
    LIBS = ['OpenMeshCore', 'harmont', 'GL', 'GLU', 'GLEW']
)

env.Program('mesh_deferred', ['mesh_deferred.cpp', 'shadow_pass.cpp', 'deferred_renderer.cpp', 'ssdo.cpp', 'rgbe.c'])
