env = Environment(
    CXXFLAGS = "-g -Wall -O2 -std=c++1y",
    CPPPATH = ['/usr/include/pcl-1.8', '/usr/include/eigen3'],
    LIBPATH = ['/usr/lib/OpenMesh'],
    LIBS = ['OpenMeshCore', 'harmont', 'GL', 'GLU', 'GLEW']
)

env.Program('test', 'test.cpp')
